# asttokens==3.0.0
# certifi==2025.8.3
# charset-normalizer==3.4.3
# decorator==5.2.1
# docutils==0.22
# executing==2.2.0
# filetype==1.2.0
# idna==3.10
# ipython==9.4.0
# ipython-pygments-lexers==1.1.1
# jedi==0.19.2
kivy==2.3.1
kivy-garden==0.1.5
kivy-garden-graph==0.4.0
# matplotlib-inline==0.1.7
# parso==0.8.4
# pexpect==4.9.0
# prompt-toolkit==3.0.51
# ptyprocess==0.7.0
# pure-eval==0.2.3
# pygments==2.19.2
# requests==2.32.4
# stack-data==0.6.3
# traitlets==5.14.3
# urllib3==2.5.0
# wcwidth==0.2.13
