name: CI
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Cython version
        run: echo `cython --version`

      # - name: Install Garden
      #   run: python -m pip install kivy-garden

      # - name: Force garden to be executable(??!)
      #   run: chmod u+x /home/runner/.local/bin/garden
      
      # - name: Check garden exists
      #   run: |
      #     which garden
      #     garden
        
      # - name: Install graph and matplotlib with Garden
      #   run: |
      #     garden install graph
      #     garden install matplotlib

      # - name: Non-legacy Graph install
      #   run: |
      #     python -m pip install kivy_garden.graph \
      #     --extra-index-url https://kivy-garden.github.io/simple/

      # - name: Leftover install...
      #   run: |
      #     python -m pip install kivy.garden.graph

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
